### ISSUE TITLE
Support for Craft 4

### ISSUE THREAD

**Issue by jayhlee** [barrelstrength/sprout-encode-email#6]
Hi Ben, I was wondering if you were planning to Sprout Encode Email for Craft 4. Thanks!

**Comment by BenParizek** [comment]
Currently, we don't plan to update this ([full list of update plans here](https://sprout.barrelstrengthdesign.com/docs/support/road-map.html)). Our focus is on our primary commercial plugins right now. I'll be updating the README's with a note shortly.

If you'd like to take over this repository and maintain it, let me know. Happy to help get you framed around migrating it on a screenshare if helpful.

**Comment by jayhlee** [comment]
Hi Ben, Thanks for letting me know. Totally understand!

**Comment by jamesmacwhite** [comment]
@engram-design FYI I submitted this plugin as part of https://verbb.io/craft-3 if there's potentially any interest in keeping it going for Craft CMS 4.

**Comment by honsa** [comment]
@BenParizek for craft4 there where just type definitions, nothing scary.

So I made a pull request for you.

You can just click and you are ready for craft4 ;)

https://github.com/barrelstrength/craft-sprout-encode-email/pull/7

**Comment by engram-design** [comment]
For anyone looking for an alternative, I'd recommend https://plugins.craftcms.com/obfuscator?craft4 which does pretty much the same thing.

**Comment by BenParizek** [comment]
This plugin will not be updated to Craft 4. It's not an issue of whether it's easy or technically possible, it is both. It's an issue of me having too much code to manage for the amount of time I have available in life, and prioritizing the time I have available for custom development with our commercial plugins. If anybody would like to fork this plugin and release something compatible with Craft 4, please do. Or, as noted above, [Obfuscator](https://plugins.craftcms.com/obfuscator?craft4) is another good option.
